src/app/widget-historical/widget-historical.component.ts

When using a darker theme with the historical data widget, it's hard to see the axis / label due to the default "black/dark grey" colour used by the widget
This PR changes legend and axis colours to match the line colour so that the legend/axis can actually be read on dark themes/night mode
Particularly relevant on tablets in high brightness with dim screens
Closes #129

Historial data widget theming

---

src/app/app-settings.service.ts
src/app/app.module.ts
src/app/notifications.service.ts
src/app/signalk-connection.service.ts
src/app/signalk-delta.service.ts
src/app/signalk-full.service.ts
src/app/signalk-interfaces.ts
src/app/signalk-requests.service.ts
src/app/signalk.service.ts

I move to the latest RsJx WebSocket implementation built on Observer. It reduces the services circular references challenges we had in some case and make socket status much simpler. Also initiated the Delta Service on app startup instead of waiting for a service to instantiate it late in the startup process. This insures the delta service is up and ready to gets messages before the connection service makes a successful connection. The app startup is fast and slick.
I fixed the WebSocket connection service to get rid of unclosed SignalK delta subscriptions caused by manual or network error reconnections. It lessens the burden on the server who, in the current implementation, was caching all delta updates for that connection until it overflowed its buffer and killed the dead connection. I …

Feature: RxJS WebSocket migration

---

src/app/app-settings.service.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/config.blank.const.ts
src/app/config.demo.const.ts
src/app/modal-user-credential/modal-user-credential.component.html
src/app/modal-user-credential/modal-user-credential.component.spec.ts
src/app/modal-user-credential/modal-user-credential.component.ts
src/app/notifications.service.ts
src/app/settings-config/settings-config.component.html
src/app/settings-config/settings-config.component.ts
src/app/settings-notifications/settings-notifications.component.ts
src/app/settings-signalk/settings-signalk.component.css
src/app/settings-signalk/settings-signalk.component.html
src/app/settings-signalk/settings-signalk.component.ts
src/app/settings-units/settings-units.component.ts
src/app/signalk-connection.service.ts
src/app/signalk-delta.service.ts
src/app/signalk-interfaces.ts
src/app/signalk-requests.service.ts
src/app/signalk.service.ts
src/app/widget-tutorial/widget-tutorial.component.html
tsconfig.json

Added login UI, login request type and token handling and expiration/renewal. Added a new connectionConfig  configuration section invalidating config up to v8. Further refinement of console.log messages to improve troubleshooting.  Also moved a few notification messages from Request Service to SignalK Config Component cleaning things up and reducing unnecessary notifications.
This PR provide a fully functional feature.
Next PR will be to add user config saving to server enabling automatic shared configuration.

feature: Support for SignalK User Authentication

---

src/app/svg-simple-linear-gauge/svg-simple-linear-gauge.component.ts

Fixes https://github.com/mxtommy/Kip/issues/140 where simple gauge doesn't show properly if `min!=0`.

fixes issue where simple linear gauge assumes min value=0

---

src/app/app-interfaces.ts
src/app/signalk-delta.service.ts
src/app/signalk-full.service.ts
src/app/signalk-interfaces.ts

Adding metadata processing to Delta service. This allows to get metadata updates post Full Document request which only happens on app connect.
- SK only sends certain data (such as boat name, width, etc) as part of deltas.
- Another usecase is if devices come online after Kip is started. Kip does not get the new device metadata info.

feature: delta meta processing

---

src/app/settings-signalk/settings-signalk.component.html
src/app/settings-signalk/settings-signalk.component.ts

Make sure we have version Signal K v1.46.2 or more. Their was a bug with CORS support in sk that crashes all secured http call (login, logout, PUT, etc.)

Block shared config on sk version

---

src/app/widget-blank/widget-blank.component.html
src/app/widget-blank/widget-blank.component.ts

Added ability to change the text of the "Blank" widget to a custom one.
The rendering has not been deliberately changed to maintain compatibility with the existing layout when using with default config.
I propose to add auto sizing here as well
I used the displayName configuration parameter to not add new parameters and keep file modifications to a minimum

On reply to the issue #85

---

src/app/config.demo.const.ts
src/app/widget-wind/widget-wind.component.ts

Changed default Wind gauge Widget default data path to self.navigation.headingTrue

Fix: default wind Widget heading data path

---

src/app/widget-gauge-ng-linear/widget-gauge-ng-linear.component.html
src/app/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
src/app/widget-gauge-ng-radial/widget-gauge-ng-radial.component.html
src/app/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
src/app/widget-simple-linear/widget-simple-linear.component.ts

Added data sub sampling time and aligned animations to same sampling time less 25ms to reduce collision.

Neddle jump fix and data sampling control

---

src/app/base-widget/base-widget.component.ts

Incompatible number decoration function when string is provided. Fixes #223

HH:MM:SS broken in 2.2.2

---

src/app/modal-path-selector/modal-path-selector.component.html
src/app/modal-path-selector/modal-path-selector.component.ts
src/app/signalk-delta.service.ts
src/app/signalk.service.ts

Fix null values parsing received from SK. Do not set KIP data type to object when values is null and wait until a value that can be set to a type is received as this prevents widget from listing appropriate path types. Fix widget Options to clear invalide sources and improve source selection dorpdown list.

Fix null values and default sources Godind/issue254

---

src/app/core/services/data-set.service.ts

Fixed blank data scrolling issue caused by SampleTime not receiving updates in the prescribde sample period.
Fixed double dataset service instance after editing datasets

Fix-chart-scrolling

---

src/app/core/services/timers.service.ts
src/app/widgets/widget-race-timer/widget-race-timer.component.ts

Changing theme causes Race Timer widget to lose track of is start/pause state

---

src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts

ng-gauge issue when title property is null. Use "" when lable is empty

Fix: empty label issue

---

src/app/app-help/app-help.component.html
src/app/widgets/widget-numeric/widget-numeric.component.ts
src/app/widgets/widget-tutorial/widget-tutorial.component.html

Instead of setting the max height to 0.075 of the canvas, set it to 0.13 of the canvas. 
This looks a little bigger, and still resizes appropriately.

Suggested edits for the tutorial and help.

---

package-lock.json
package.json
src/app/alarm-menu/alarm-menu.component.html
src/app/alarm-menu/alarm-menu.component.scss
src/app/alarm-menu/alarm-menu.component.ts
src/app/app.component.ts
src/app/core/interfaces/app-interfaces.ts
src/app/core/interfaces/signalk-interfaces.ts
src/app/core/interfaces/widgets-interface.ts
src/app/core/services/app-service.ts
src/app/core/services/notifications.service.ts
src/app/core/services/signalk-data.service.ts
src/app/core/services/signalk-delta.service.ts
src/app/core/services/signalk-requests.service.ts
src/app/settings/config/config.component.ts
src/app/settings/general/general.component.html
src/app/settings/general/general.component.ts
src/app/settings/signalk/signalk.component.ts
src/app/settings/units/units.component.ts
src/app/widgets/widget-boolean-switch/widget-boolean-switch.component.ts
src/app/widgets/widget-button/widget-button.component.ts
src/app/widgets/widget-login/widget-login.component.ts
src/main.ts
src/tsconfig.app.json

Rewrite of notification Service, Menu and related service dependency.
Fixes empty menu notification. Reduced service dependency.
Now uses SK state and method notification properties and publishes notifications updates to SK instead of using a local notifiaction management system. This increases KIP/SK integration.
KIP now requires SK Alarm Silencer plugin to clear and silence alar - required to update notifications.
Issue: Zones also use a local service and so Zones notifications cannot be silenced or cleared until Zones are rebuilt to use ZK integrated Zones.

rewrite: empty notification Godind/issue317

---

package-lock.json
package.json
src/app/app.component.scss
src/styles.scss

Enlarged navbar button to support MDC control new touch-tagert of 46px applied to buttons to improve touch device control touch area. This is causing scrollbar to appear as the touch area of the navbar buttons overflows to the buttom of the screen.

fix: Chrome scrolbar issue with MDC touch-target

---

src/app/widget-config/boolean-multicontrol-options/boolean-multicontrol-options.component.ts
src/app/widget-config/modal-widget-config/modal-widget-config.component.html
src/app/widget-config/modal-widget-config/modal-widget-config.component.ts
src/app/widget-config/path-control-config/path-control-config.component.ts

fix wind widget path update issue and add form validation after update

fix wind widget path update issue and form validation

---

CHANGELOG.md
package.json
src/app/core/services/data.service.ts
src/app/widget-config/path-control-config/path-control-config.component.ts

Update 2.10.0: values jumping between sources

---

src/app/widget-config/modal-widget-config/modal-widget-config.component.html
src/app/widgets/gauge-steel/gauge-steel.component.ts
src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
src/app/widgets/widget-gauge-steel/widget-gauge-steel.component.html
src/app/widgets/widget-gauge-steel/widget-gauge-steel.component.ts

Fixes #428
* Add support for decimals to steel gauges
* Makes integer and decimal form control required
* Set Interger form control value range of 1 - 5
* Add fallback values to gauges.

Add support for decimal places to Steel Style gauge

---

package-lock.json
src/app/core/interfaces/widgets-interface.ts
src/app/widget-config/modal-widget-config/modal-widget-config.component.html
src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
src/app/widgets/widget-gauge-steel/widget-gauge-steel.component.ts

This adds a "highlights width" property to the radial gauge config with a range of `0-25`.  It still defaults to `5`, but that value is too skinny for my old eyes.
It also looks like there's a bug that prevents zones (and therefore highlights) from being available on initial load.  I clumsily fixed this in the 2nd commit by moving `initWidget()` after `observeDataStream()`, otherwise it seems the data service `_pathRegister` isn't loaded when the gauge tries to subscribe to metadata.  There's probably a better way to solve this, but it felt that would require a more fundamental change that would affect all widgets (although other widgets likely have this problem, too).

Makes ng-gauge highlights width configurable

---

src/app/base-widget/base-widget.component.ts

This moves `observeMeta()` to after `createDataObservable()` so that the subscription path is ensured to be loaded when the gauge is initially rendered.  Without this, zone data may not be available, causing highlights to not render.

Fixes issue with metadata not being available on initial load

---

src/app/core/services/units.service.ts

dervied-data can produce fuel-economy paths that show up as m/m^3. Most of us don't think in meters per cubic-meter, even if we love the metric system a whole lot. Add a set of reasonable units for displaying fuel economy. Showing this along-side fuel flow rate can be helpful.

Add fuel economy units

---

src/app/core/services/canvas.service.ts
src/app/core/services/data.service.ts
src/app/core/services/units.service.ts
src/app/widgets/widget-position/widget-position.component.ts

Fixes #654
1- Remove the default deg to rad conversion for paths containing *.position.*
2- Remove Position format group reconversion from rad to deg before formatting to string representation
3- adjust Position widget to correct standard.
4- Cleanup units group listing
5- Fix canvas drawing overlap

Position Paths Should Not Be Converted To Radian

---

CHANGELOG.md
package.json
src/app/core/services/signalk-delta.service.ts

Update the Vessel Base Delta path handling to stop removing the first character of Vessel Delta.

Fix stripped Vessel Base Delta path

---

src/app/core/utils/themeColors.utils.spec.ts
src/app/core/utils/zones-highlight.utils.spec.ts

Delete obsolete unit tests for the themeColors and zonesHighlight utilities to streamline the codebase.

Remove unused unit tests for themeColors and zonesHighlight utilities

---

src/app/widget-config/modal-widget-config/modal-widget-config.component.html

Adjust the visibility condition for the paths tab label to account for the disabled state, ensuring proper display when the form is not valid or disabled.

Update paths tab label visibility condition

---

src/app/widgets/widget-boolean-switch/widget-boolean-switch.component.html
src/app/widgets/widget-boolean-switch/widget-boolean-switch.component.ts
src/app/widgets/widget-datetime/widget-datetime.component.html
src/app/widgets/widget-datetime/widget-datetime.component.ts
src/app/widgets/widget-numeric/widget-numeric.component.html
src/app/widgets/widget-numeric/widget-numeric.component.ts
src/app/widgets/widget-position/widget-position.component.html
src/app/widgets/widget-position/widget-position.component.ts
src/app/widgets/widget-slider/widget-slider.component.html
src/app/widgets/widget-slider/widget-slider.component.ts
src/app/widgets/widget-text/widget-text.component.html
src/app/widgets/widget-text/widget-text.component.ts

Refactor the color management in widget components by replacing the `labelColor` and `barColor` properties with signals for better reactivity and updating the color retrieval logic accordingly.

Refactor color handling in widget components

---

src/app/app.routes.ts
src/app/core/components/dashboard/dashboard.component.html
src/app/core/components/dashboard/dashboard.component.ts
src/app/core/services/dashboard.service.ts
src/app/widgets/widget-racer-timer/widget-racer-timer.component.ts

Enable selection of specific dashboards via URL, allowing users to bookmark their dashboard views. This change enhances navigation by integrating dashboard IDs into the routing structure.
Fixes #638

Add dashboard number to URL for bookmarking

---

src/app/widgets/widget-freeboardsk/widget-freeboardsk.component.ts
src/app/widgets/widget-iframe/widget-iframe.component.ts

Updated the swipe gesture handling for the Freeboard-SK and Embed widgets to correctly navigate between dashboards. This resolves the issue where swipe gestures were recognized but did not change the displayed dashboard.
Fixes #743

Fix dashboard swipe gesture functionality in Freeboard-SK and Embed widgets

---

src/app/core/services/canvas.service.ts
src/app/widgets/widget-datetime/widget-datetime.component.ts
src/app/widgets/widget-numeric/widget-numeric.component.ts
src/app/widgets/widget-position/widget-position.component.ts
src/app/widgets/widget-racer-line/widget-racer-line.component.ts
src/app/widgets/widget-racer-timer/widget-racer-timer.component.ts
src/app/widgets/widget-text/widget-text.component.ts

Implement checks for bitmap dimensions before drawing to prevent rendering issues with zero-size bitmaps. This enhances the stability of canvas rendering across various components.

Fix canvas rendering by adding checks for bitmap dimensions

---

src/app/widgets/widget-racer-timer/widget-racer-timer.component.html

The startAt time cannot be set on android browser as there is no enter key.
This fixes that issue

Fix the startAt time selection when using mobile browser

---

README.md
src/assets/help-docs/community.md
src/assets/help-docs/configuration.md
src/assets/help-docs/contact-us.md
src/assets/help-docs/dashboards.md
src/assets/help-docs/datainspector.md
src/assets/help-docs/datasets.md
src/assets/help-docs/embedwidget.md
src/assets/help-docs/grafana.md
src/assets/help-docs/influxdb.md
src/assets/help-docs/kiosk.md
src/assets/help-docs/menu.json
src/assets/help-docs/putcontrols.md
src/assets/help-docs/welcome.md
src/assets/help-docs/zones.md

Enhance the 'Contact Us', 'Dashboards', 'Digital Switching', and 'Welcome' sections to improve user understanding and engagement. Adjust titles and content for better clarity and usability.

Update help documentation for clarity and detail
