- src/app/data-set.service.ts
- src/app/signalk.service.ts
- src/app/widget-gauge/widget-gauge.component.ts
- src/app/widget-numeric/widget-numeric.component.ts
- src/app/widget-text-generic/widget-text-generic.component.ts
- src/app/widget-wind/widget-wind.component.ts
Simplify subscriptions bu returning just value (by asking for source we want in sub)
> Subscription service

- src/index.html
Fix font-awesome being loaded as an absolute url. Without relative pathing this will break fonts when loaded via signalk
> Update index.html in platform_upgrade

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/timers.service.spec.ts
- src/app/timers.service.ts
- src/app/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widget-list.service.ts
- src/app/widget-manager.service.ts
- src/app/widget-race-timer/widget-race-timer.component.html
- src/app/widget-race-timer/widget-race-timer.component.scss
- src/app/widget-race-timer/widget-race-timer.component.spec.ts
- src/app/widget-race-timer/widget-race-timer.component.ts
- src/styles.scss
Been a while :) Added a race timer for starts.
Removed @biacsics/ng-canvas-gauges as a dependency as I moved the code into `src/app/gauges-module` as there was a bug in that module that wasn't getting fixed (see https://github.com/biacsics/ng-canvas-gauges/pull/1 )
If all is good feel free to merge!
> Added Widget Race Timer

- src/app/units.service.ts
resolves https://github.com/mxtommy/Kip/issues/139 to add new Units
> adds Ah and kWh units

- package-lock.json
- package.json
- src/app/app-interfaces.ts
- src/app/app-settings.interfaces.ts
- src/app/data-browser/data-browser.component.ts
- src/app/modal-path-selector/modal-path-selector.component.ts
- src/app/notifications.service.ts
- src/app/settings-datasets/settings-datasets.component.ts
- src/app/settings-zones/settings-zones.component.ts
- src/app/signalk-delta.service.ts
- src/app/signalk-full.service.ts
- src/app/signalk-interfaces.ts
- src/app/signalk-requests.service.ts
- src/app/signalk.service.ts
- src/app/storage.service.ts
- src/app/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
- src/app/widget-numeric/widget-numeric.component.ts
- src/app/widget-race-timer/widget-race-timer.component.ts
Added metadata processing to Delta service. This allows to get metadata updates post Full Document request which only happens on app connect.
- SK only sends certain data (such as boat name, width, etc) as part of deltas.
- Another usecase is if devices come online after Kip is started. Kip does not get the new device metadata info.
> Feature: Delta Service Metadata Processing

- src/app/app-initNetwork.service.ts
- src/app/app-settings.service.ts
- src/app/reset-config/reset-config.component.html
- src/app/settings-signalk/settings-signalk.component.html
- src/app/storage.service.ts
Fix the error generated by the sk applicationData/user/default key not existing on first time login.
We now create a default key with defaultConfig and restart the app.
Also fixed a few Undefined check and minor UI adjustments
> fix: null default key error

- src/app/widget-button/widget-button.component.html
- src/app/widget-button/widget-button.component.scss
- src/app/widget-button/widget-button.component.ts
Feature: Added light indicator to Switch/Button Widget
> Boolean-Switch-widget-Update

- angular.json
- package-lock.json
- package.json
- src/app/widgets/widget-historical/widget-historical.component.ts
removed moment.js and used a lighter chart.js datatime library the supports ESM module for smaller app size
> UDM module cleanup

- src/app/base-widget/base-widget.component.ts
> Latitude and Longitude format

- src/app/units.service.ts
> BUG: West Longitudes show negatives

- src/app/modal-path-selector/modal-path-selector.component.html
- src/app/modal-path-selector/modal-path-selector.component.scss
- src/app/modal-path-selector/modal-path-selector.component.ts
Added Sample Time property to Widget Paths options modal allowing to set Observer sampleTime filter value.
> Add-sampleTime-property-to-Widget-Paths-option

- src/app/app-help/app-help.component.html
- src/app/app-initNetwork.service.ts
- src/app/app-settings.service.ts
- src/app/settings/config/config.component.html
- src/app/settings/config/config.component.scss
- src/app/settings/config/config.component.ts
- src/app/settings/signalk/signalk.component.html
- src/app/storage.service.ts
Fixed Device Token upgrade issues and added ability to list and upgrade v1 config files on remote storage.
> Upgrade-remove-v1-remote-storage-config-file

- src/app/app.service.ts
- src/app/widgets/svg-wind/svg-wind.component.ts
> Typo in function for "Night Vision"

- src/app/base-widget/base-widget.component.ts
- src/app/units.service.ts
> undefine value causing toFix() issue

- src/app/signalk.service.ts
- src/app/widgets/widget-date-generic/widget-date-generic.component.ts
> Add type datetime to path and path filter

- CHANGELOG.md
- src/app/base-widget/base-widget.component.ts
> Error: Unable to convert "--" into a date (version 2.4.0)

- src/app/modal-widget-config/modal-widget-config.component.html
- src/app/widgets/svg-wind/svg-wind.component.html
- src/app/widgets/svg-wind/svg-wind.component.ts
- src/app/widgets/widget-wind/widget-wind.component.html
> Wind Instrument "Laylines" label incorrect and port/starboard colors inverted

- src/app/widgets/svg-autopilot/svg-autopilot.component.html
- src/app/widgets/widget-autopilot/widget-autopilot.component.scss
Modified the style sheet on autopilot widget to make numbers more visible on the compass ring with the dark modern theme.
Fixing  #268
> Modified the style sheet on autopilot widget

- src/app/widget-config/modal-widget-config/modal-widget-config.component.html
- src/app/widget-config/modal-widget-config/modal-widget-config.component.ts
- src/app/widget-config/path-control-config/path-control-config.component.html
Fixes #275. Added path group enabling based on widget Display Options prenventing saving of the form.
> It is not possible to save wind widget with paths errors

- src/app/app-initNetwork.service.ts
- src/app/app-settings.service.ts
- src/app/config.blank.const.ts
> Add Server auto-discovery

- src/app/app.service.ts
> Use  environment.mode for Night mode

- src/app/app-initNetwork.service.ts
- src/app/app.module.ts
- src/app/settings/signalk/signalk.component.html
- src/app/signalk-connection.service.ts
- src/index.html
- src/manifest.json
- src/styles.css
Fixes #273 with a new spinner loader until APP_INITIALYZER completes or times out
> Blank screen on bad server address

- src/app/settings/config/config.component.html
- src/app/settings/config/config.component.ts
Fixes #271 with an improved error message and possible resolution guidance.
> [object Object] error message

- package-lock.json
- package.json
- public/3rdpartylicenses.txt
- public/index.html
Dry update. No issues. Need to update to Angular material to MDC- based components to remove legacy component and styles support.
> Angular-16-upgrade

- angular.json
- package-lock.json
- package.json
- src/app/widgets/widget-tutorial/widget-tutorial.component.html
MDC component and syles migration still required but works fine with Legacy Material artifacts.
> Angular-17-upgrade

- package-lock.json
- package.json
> angular-split update

- CHANGELOG.md
- src/app/alarm-menu/alarm-menu.component.html
- src/app/alarm-menu/alarm-menu.component.scss
- src/app/app.component.html
- src/app/app.component.scss
Fixed nav-bar menus icon issues on Chromium.
Fixed Config version Upgrade issues
> Fix Chromium & Config Upgrade Issues

- src/app/core/services/authentication.service.ts
Added NEVER expire token support. Fixes #318
> Login/Logout Authentication Infinite Loop

- src/app/core/services/signalk.service.ts
> Negative zone alarms triggering incorrectly

- src/app/settings/zones/zones.component.css
- src/app/settings/zones/zones.component.html
Fix edit and delete button alignment.
> Fix table layout

- src/app/settings/signalk/signalk.component.html
- src/app/settings/signalk/signalk.component.scss
> Signal K layout improvements

- src/app/core/services/widget-list.service.ts
- src/default-config/config.demo.const.ts
Add widget color and Feeboard-SK widget
> demo config update

- src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
> Radial gauge numbers displayed incorrectly

- src/app/widgets/gauge-steel/gauge-steel.component.ts
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
- src/app/widgets/widget-gauge/widget-gauge.component.html
- src/app/widgets/widget-gauge/widget-gauge.component.ts
Fixes #348: Zones area drawing did not support path format conversion.
> fix: radial and inear gauges zones not drawn to proper units

- src/app/base-widget/base-widget.component.ts
- src/app/core/services/signalk-data.service.ts
- src/app/core/services/units.service.ts
- src/app/data-browser-row/data-browser-row.component.ts
- src/app/widgets/gauge-steel/gauge-steel.component.ts
- src/app/widgets/widget-data-chart/widget-data-chart.component.ts
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
Additional fixes to #348 for non-standard KIP units support
> Zones displayed incorrectly if zone and gauge units don't match

- src/app/core/services/app-service.ts
increased timeout from 0 to 1500ms for that path data has time to be received from SK
> Fix: increase path data query timeout

- src/app/core/interfaces/widgets-interface.ts
- src/app/core/services/layout-splits.service.ts
- src/app/data-browser/data-browser.component.html
- src/app/data-browser/data-browser.component.ts
- src/app/layout-split/layout-split.component.ts
- src/app/settings/zones/new-zone.modal.html
- src/app/settings/zones/zones.component.ts
- src/app/widget-config/boolean-multicontrol-options/boolean-multicontrol-options.component.html
- src/app/widget-config/boolean-multicontrol-options/boolean-multicontrol-options.component.ts
- src/app/widget-config/modal-widget-config/modal-widget-config.component.html
- src/app/widget-config/modal-widget-config/modal-widget-config.component.ts
- src/app/widgets/svg-autopilot/svg-autopilot.component.ts
- src/app/widgets/svg-boolean-switch/svg-boolean-switch.component.ts
- src/app/widgets/svg-simple-linear-gauge/svg-simple-linear-gauge.component.ts
- src/app/widgets/widget-boolean-switch/widget-boolean-switch.component.ts
- tsconfig.json
This pull request enables Angular strictTemplates for better template typing. It also fixes a type error in multiple forms.
It also includes other minor code improvements and bug fixes.
> feat: enable strictTemplates

- src/app/alarm-menu/alarm-menu.component.html
- src/app/alarm-menu/alarm-menu.component.ts
- src/app/core/interfaces/app-interfaces.ts
- src/app/core/interfaces/signalk-interfaces.ts
- src/app/core/services/notifications.service.ts
- src/app/core/services/signalk-data.service.ts
- src/app/core/services/signalk-delta.service.ts
Added processing of Edit Zones notification plugin updates. Reachitecture of Notification Value and Meta updates. Fix notification service and menu.
> Added SK Notification update to sk-delta.service. Clean up of Notification.service and menu

- src/app/core/services/signalk-data.service.ts
Also fixed comented local Method push issue... if we ever bring this code back.
> Commented local zones push notifications

- package-lock.json
- package.json
- src/app/alarm-menu/alarm-menu.component.html
- src/app/alarm-menu/alarm-menu.component.scss
Chromium does not support css fit-content. Use max-content  for same result.
> fix: Chromium nemi styling

- src/app/core/services/notifications.service.ts
Fixes Silence Audio where method audio is removed.
Removed Notifications array reset on config changes
> Fix--notification-setting-update-and-clearing-of-MOB

- src/app/settings/signalk/signalk.component.html
URL for the demo server is https://demo.signalk.org, not https://demo.signalk.com
> Use correct URL - demo.signalk.org

- src/app/alarm-menu/alarm-menu.component.html
- src/app/alarm-menu/alarm-menu.component.scss
- src/app/alarm-menu/alarm-menu.component.ts
- src/app/core/services/notifications.service.ts
Readd mute button and adjust actions menu icons and labels.
> add mute button and change actions menu icons

- src/app/core/services/app-settings.service.ts
Fixes #398 Demo config not loading with sign-in connection option.
> Demo display not persistant from demo to signed in mode

- package-lock.json
- package.json
- src/app/core/interfaces/widgets-interface.ts
- src/app/core/services/widget-list.service.ts
- src/app/widget-config/modal-widget-config/modal-widget-config.component.html
- src/app/widget-config/path-control-config/path-control-config.component.ts
- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.html
- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.scss
- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.spec.ts
- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.ts
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.html
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.scss
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
*Add Compass Widget and fix plate animation
*Update Widget Options
*Update Linear gauge to include ticks by default and used nice scales and ticks
> Add-ng-compass-gauge

- src/app/core/interfaces/widgets-interface.ts
- src/app/widget-config/path-control-config/path-control-config.component.html
- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.ts
> feat: add compas support for Rad units with negative to port

- src/app/core/services/data-set.service.ts
Uses the most recent datapoints and not the oldest.
> Fix SMA calculation

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/core/interfaces/widgets-interface.ts
- src/app/widget-config/modal-widget-config/modal-widget-config.component.html
- src/app/widgets/widget-autopilot/widget-autopilot.component.ts
> N2K Autopilot rudder gauge sensor emitting inverted values

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/widgets/widget-numeric/widget-numeric.component.ts
> Numeric value not converting to HH:MM:SS format

- package-lock.json
- package.json
- src/app/core/components/dashboard-editor/dashboard-editor.component.html
- src/app/core/components/dashboard-editor/dashboard-editor.component.scss
- src/app/core/components/dashboard-editor/dashboard-editor.component.ts
- src/app/core/components/dashboard/dashboard.component.html
- src/app/core/components/dashboard/dashboard.component.ts
Update Gridstack and fix grid editor widget category filter breaking drag & drop DOM events. Isssue was the DOM was not fully loaded so the events were never added after category change.
> Fix dashboard editor widget list filtering

- src/app/core/components/menu-actions/menu-actions.component.html
- src/app/core/components/menu-actions/menu-actions.component.ts
- src/assets/svg/icons.svg
- reorg top & bottom action navbar buttons
- update icons
> reorg action menu

- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.scss
- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.ts
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
- Remove tick solors and make value color follow zones colors
- Fix gauge positionning and resizing on load and on config update.
> Fix-guage-colors-and resize

- package.json
- src/app/core/components/dashboard/dashboard.component.ts
- src/app/core/utils/base-widget.component.ts
- src/app/widgets/widget-autopilot/widget-autopilot.component.ts
- src/app/widgets/widget-boolean-switch/widget-boolean-switch.component.ts
- src/app/widgets/widget-data-chart/widget-data-chart.component.ts
- src/app/widgets/widget-datetime/widget-datetime.component.ts
- src/app/widgets/widget-freeboardsk/widget-freeboardsk.component.ts
- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.ts
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
- src/app/widgets/widget-gauge-steel/widget-gauge-steel.component.spec.ts
- src/app/widgets/widget-gauge-steel/widget-gauge-steel.component.ts
- src/app/widgets/widget-iframe/widget-iframe.component.ts
- src/app/widgets/widget-numeric/widget-numeric.component.html
- src/app/widgets/widget-numeric/widget-numeric.component.ts
- src/app/widgets/widget-race-timer/widget-race-timer.component.ts
- src/app/widgets/widget-simple-linear/widget-simple-linear.component.ts
- src/app/widgets/widget-text/widget-text.component.ts
- src/app/widgets/widget-tutorial/widget-tutorial.component.ts
- src/app/widgets/widget-unknown/widget-unknown.component.ts
- src/app/widgets/widget-wind/widget-wind.component.ts
- Fix gauge zones reload
- Fix Numeric zones color and state to align with gauges
> Fix-load-zones-data-and-colors

- package.json
- src/app/core/components/dashboard/dashboard.component.ts
- src/app/widgets/widget-autopilot/widget-autopilot.component.ts
- src/app/widgets/widget-tutorial/widget-tutorial.component.ts
-Do not copy widgetProperties on widget creation.
- Code Cleanup
> Fix-add-delete-config-duplication

- src/app/app.component.html
- src/app/app.component.ts
- src/app/core/components/dashboard/dashboard.component.html
- src/app/core/components/dashboard/dashboard.component.ts
- src/app/core/components/menu-notifications/menu-notifications.component.html
- src/app/core/components/menu-notifications/menu-notifications.component.ts
- src/app/core/components/notification-badge/notification-badge.component.html
- src/app/core/components/notification-badge/notification-badge.component.scss
- src/app/core/components/notification-badge/notification-badge.component.spec.ts
- src/app/core/components/notification-badge/notification-badge.component.ts
- src/app/core/services/notifications.service.ts
- Removed glitchy button and badge and replace with floating FAB button and badge.
- clean up of Observable in favor if toSignal()
- minor rearchitecture of Notification fonctions.
> Fixed notification prompt component

- src/app/settings/signalk/signalk.component.html
- src/app/settings/signalk/signalk.component.ts
Removed Device Token from Connection page UI only. All the code is still present.
> Remove device token option

- src/app/core/services/widget.service.ts
- src/app/widgets/widget-position/widget-position.component.ts
> Adjust position widget

- src/app/widgets/widget-numeric/widget-numeric.component.ts
> fix numeric init colour

- src/app/core/components/dashboard/dashboard.component.html
- src/app/core/components/dashboard/dashboard.component.ts
- src/app/core/services/dashboard.service.ts
Fix effect() with Subject instead to prevent llop and change detection issue
> Fix effect

- src/app/app.component.ts
- src/app/core/components/dashboard/dashboard.component.ts
- src/app/widgets/widget-tutorial/widget-tutorial.component.html
Add Shift + Ctrl to arrow key to prevent edit field collision
> Adjust-hotkey

- src/app/core/interfaces/widgets-interface.ts
- src/app/widget-config/modal-widget-config/modal-widget-config.component.html
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
- src/app/widgets/widget-gauge-steel/widget-gauge-steel.component.ts
- src/app/widgets/widget-numeric/widget-numeric.component.ts
Add zones display option to Numeric, Radial, Linear and Steel widgets.
> Add zones display option

- src/app/core/components/menu-notifications/menu-notifications.component.html
- src/app/core/components/menu-notifications/menu-notifications.component.scss
- src/index.html
- Fix massega overflow and scroll
- Add hover over long paths
- Add overflow to long messages
- Add new mobile meta tag to main page
> Fix Nortfication menu

- package.json
- src/app/app.component.ts
- src/app/core/components/dashboard-scroller/dashboard-scroller.component.scss
- src/app/core/components/menu-actions/menu-actions.component.html
- src/app/core/components/menu-actions/menu-actions.component.ts
- src/app/core/services/app-service.ts
- src/app/core/services/app-settings.service.ts
- src/app/core/services/uiEvent.service.ts
- src/app/settings/display/display.component.html
- src/app/settings/display/display.component.ts
- Remove scroller input events trapping.
- imporved trapping of screen edge swipe browser default event
> Fix swipes

- src/app/widget-config/display-datetime/display-datetime.component.html
- src/app/widget-config/display-datetime/display-datetime.component.ts
- src/app/widgets/widget-datetime/widget-datetime.component.ts
Update DateTime widget to fix timezone support
> Fix timezone display

- package.json
- src/app/core/components/menu-actions/menu-actions.component.scss
- src/app/core/components/menu-notifications/menu-notifications.component.scss
fix scroll in Actions and Notifications sidenav
> scroll fix

- src/app/app.routes.ts
- Lazy-load everything execpt Dashboard
> Add component lazy-loading

- src/app/core/interfaces/widgets-interface.ts
- src/app/widget-config/modal-widget-config/modal-widget-config.component.html
- src/app/widgets/svg-boolean-button/svg-boolean-button.component.ts
- src/app/widgets/svg-boolean-light/svg-boolean-light.component.ts
- src/app/widgets/svg-boolean-switch/svg-boolean-switch.component.ts
- src/app/widgets/widget-boolean-switch/widget-boolean-switch.component.ts
- src/app/widgets/widget-data-chart/widget-data-chart.component.ts
- src/app/widgets/widget-datetime/widget-datetime.component.ts
- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.ts
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.scss
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
- src/app/widgets/widget-label/widget-label.component.ts
- src/app/widgets/widget-numeric/widget-numeric.component.ts
- src/app/widgets/widget-race-timer/widget-race-timer.component.ts
- src/app/widgets/widget-simple-linear/widget-simple-linear.component.ts
- src/app/widgets/widget-text/widget-text.component.ts
- src/default-config/config.demo.const.ts
- fix resize aspect ratio
- add needle option
- add needle colour support
> Linear gauge improvements

- src/app/widgets/widget-gauge-ng-compass/widget-gauge-ng-compass.component.ts
- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
- src/app/widgets/widget-gauge-ng-radial/widget-gauge-ng-radial.component.ts
- src/styles.scss
- Fix Compass and other ng gauge template acces before viewInit
- Fix app load spinner not centered
> Fix firefox UI issue

- src/app/widgets/svg-boolean-button/svg-boolean-button.component.svg
- src/app/widgets/svg-boolean-switch/svg-boolean-switch.component.svg
- Fixes #568
- Does NOT FIX #556: Bad tagging.
> Fix Toggle Switches Boolean Control Panel - Push mode not not changing color with touchscreen

- src/app/core/services/authentication.service.ts
> Token renewal loop

- src/app/core/services/units.service.ts
> Conversion of seconds to HH:MM:SS loses sign

- package.json
- src/app/app.component.ts
- src/app/settings/display/display.component.html
- src/app/settings/display/display.component.ts
- src/app/settings/notifications/notifications.component.html
- src/app/settings/notifications/notifications.component.ts
add phone portait
- Display and Notification accordeon description responsive
- Single sivenar (autoclose)
> Portrait-phone-responsive

- package.json
- src/app/core/components/app-help/app-help.component.html
- src/app/core/components/menu-actions/menu-actions.component.html
- src/app/core/components/widgets-list/widgets-list.component.html
- src/app/core/services/units.service.ts
- src/app/settings/units/units.component.html
- src/app/widget-config/boolean-control-config/boolean-control-config.component.html
- src/app/widget-config/boolean-control-config/boolean-control-config.component.ts
- src/app/widget-config/boolean-multicontrol-options/boolean-multicontrol-options.component.html
- src/app/widget-config/boolean-multicontrol-options/boolean-multicontrol-options.component.ts
- src/app/widget-config/dataset-chart-options/dataset-chart-options.component.html
- src/app/widget-config/display-chart-options/display-chart-options.component.html
- src/app/widget-config/modal-widget-config/modal-widget-config.component.html
- src/app/widget-config/path-control-config/path-control-config.component.html
- src/app/widget-config/paths-options/paths-options.component.html
- src/app/widgets/widget-boolean-switch/widget-boolean-switch.component.scss
- add inch and millimeter units
- fix for loop and changed after view
> fix plus add inch and millimeter units

- package-lock.json
- package.json
- src/app/widget-config/display-chart-options/display-chart-options.component.ts
- src/app/widgets/widget-data-chart/widget-data-chart.component.bak
- src/app/widgets/widget-data-chart/widget-data-chart.component.html
- src/app/widgets/widget-data-chart/widget-data-chart.component.spec.ts
- src/app/widgets/widget-data-chart/widget-data-chart.component.ts
- temporarly remove Streaming plugin
> Disable-data-chart-streaming

- package.json
- src/app/widgets/widget-iframe/widget-iframe.component.html
- src/app/widgets/widget-iframe/widget-iframe.component.ts
> Embedded Web Page not working after 3.0 upgrade

- src/app/core/services/app-service.ts
- src/app/core/services/signalk-plugins.service.spec.ts
- src/app/core/services/signalk-plugins.service.ts
- src/app/settings/display/display.component.ts
- Add support for Signal K v2 Features API enabling server plugin presence and status validation
- Update Automatic night mode to rely on new signalk-plugins service
> Sk-plugin-dependency-validation

- package.json
- src/app/app.component.ts
- src/app/core/interfaces/widgets-interface.ts
- src/app/widget-config/modal-widget-config/modal-widget-config.component.html
- src/app/widgets/widget-freeboardsk/widget-freeboardsk.component.ts
- src/app/widgets/widget-iframe/widget-iframe.component.html
- src/app/widgets/widget-iframe/widget-iframe.component.ts
> Allow input to embed webpage elements

- src/app/widgets/widget-data-chart/widget-data-chart.component.ts
fixes Data Chart not changing to red night mode.
> fix data chart night mode

- src/app/core/services/data.service.ts
- src/app/widget-config/path-control-config/path-control-config.component.ts
- Limit supportsPUT path filter the Signal K server version 2.12+. Prior versions do not support this meta and so no paths will ever be returned.
> limit supportsPut filter to SK v2.12 and more

- src/main.ts
from velocity: 0.6, threshold: 20 to velocity: 0.3, threshold: 10
> add swipe sensitivity

- src/app/widgets/widget-gauge-ng-linear/widget-gauge-ng-linear.component.ts
> Linear gauge not respecting scales with no ticks

- src/app/core/services/signalk-delta.service.ts
Add documment visibility observable to handle app resume auto reconnection on mobile and tablets.
> Add app visibility handling

- src/app/core/components/dashboard/dashboard.component.scss
- src/app/core/components/widget-title/widget-title.component.html
- src/app/core/components/widget-title/widget-title.component.scss
- Fix Title resize event tagged to wrong element.
-Fix dashboard component has a scrollbar on Firefox due to 0.5px round issue on this bowser.
Fixes #635
> Numeric Widget Has Scrollbar on Resize

- src/app/widgets/widget-data-chart/widget-data-chart.component.ts
> fix dataset length

- src/app/core/services/widget.service.ts
Update widget service to correct plugin dependencies for various components, ensuring proper functionality and reducing unnecessary dependencies.
> Fix plugin dependencies for widgets

- package.json
- src/app/widgets/widget-autopilot/widget-autopilot.component.html
- src/app/widgets/widget-autopilot/widget-autopilot.component.scss
- src/app/widgets/widget-autopilot/widget-autopilot.component.ts
Enhance the menu and button functionality for different freeze modes, including adjustments to item states and visual styles.
> Menu and button adjustments for freeze modes

- src/app/widgets/widget-slider/widget-slider.component.ts
Introduce options for configuring path unit conversion in the widget slider, enhancing flexibility for users.
> Add support for configurable path unit conversion in widget slider

- src/app/core/components/dashboard/dashboard.component.html
- src/app/core/components/dashboard/dashboard.component.scss
- src/app/core/components/dashboard/dashboard.component.ts
Improve the user experience for empty dashboards by adding customizable actions and enhanced styling options. Users can now unlock and customize their dashboard or add widgets directly from the empty state.
> Enhance empty dashboard state with actions and styling

- src/assets/help-docs/menu.json
> Relabel Help index titles

- src/app/app.component.ts
- src/app/core/components/modal-user-credential/modal-user-credential.component.html
- src/app/core/services/app-initNetwork.service.ts
- src/app/core/services/connection-state-machine.service.ts
- src/app/core/services/signalk-connection.service.ts
- src/app/core/services/signalk-delta.service.ts
- src/app/settings/signalk/signalk.component.html
- src/app/settings/signalk/signalk.component.ts
- src/main.ts
- Added ConnectionStateMachine service to manage connection states and retries for HTTP and WebSocket connections.
- Refactored SignalKConnectionService to utilize ConnectionStateMachine for connection initialization and error handling.
- Implemented connection validation before establishing a connection in SettingsSignalkComponent.
- Updated SignalKDeltaService to handle WebSocket connections through ConnectionStateMachine, including retry logic.
- Improved user experience by updating the connect button state during connection validation.
- Added new methods for managing connection states and retries in ConnectionStateMachine.
- Enhanced modal-user-credential component to improve password input handling.
> feat: Enhance connection handling with ConnectionStateMachine

- CHANGELOG.md
- package.json
- src/app/widget-config/modal-widget-config/modal-widget-config.component.ts
- src/app/widget-config/path-control-config/path-control-config.component.ts
Improve path configuration by adding autopilot support and validating path groups. Update version and CHANGELOG for the new release.
> Enhance path handling and update version to 3.4.1

- src/main.ts
Replaced depricated APP_INITIALYZE initialization process to utilize `provideAppInitializer`.
> Replace depricated APP_INITIALYZE

- src/app/widgets/svg-autopilot/svg-autopilot.component.svg
Adjust the positioning of text elements for better display of locked headings in the SVG.
> Fix text positioning for locked heading in SVG

- package.json
- src/app/widgets/widget-racer-line/widget-racer-line.component.scss
- src/app/widgets/widget-racer-line/widget-racer-line.component.ts
- src/app/widgets/widget-racer-timer/widget-racer-timer.component.scss
- src/app/widgets/widget-racer-timer/widget-racer-timer.component.ts
Adjust widget dimensions for better layout and enhance color handling by utilizing a centralized color function.
> Fix widget dimensions and improve color handling in racer components

- src/app/core/components/menu-actions/menu-actions.component.scss
- src/app/core/components/menu-notifications/menu-notifications.component.scss
- src/app/widgets/svg-simple-linear-gauge/svg-simple-linear-gauge.component.svg
- src/app/widgets/widget-freeboardsk/widget-freeboardsk.component.html
Adjust overflow properties for menu components to improve usability and increase the highlight height in the gauge for better visibility.
> Update overflow properties and highlight height in gauge

- src/app/widgets/widget-numeric/widget-numeric.component.ts
Enhance text alignment in the drawUnit and drawMinMax methods for better visual consistency. Adjustments include refined margins and alignment settings.
> Improve text positioning in drawUnit and drawMinMax methods

- src/app/app.component.ts
- src/app/core/services/connection-state-machine.service.ts
Adjust WebSocket retry intervals to improve connection handling and enhance logging for connection status updates. This change aims to provide clearer feedback during connection attempts and retries.
> Update WebSocket retry intervals and enhance connection logging

- src/app/core/services/app-initNetwork.service.ts
- src/app/core/services/app-settings.service.ts
- src/app/core/services/authentication.service.ts
- src/app/core/services/storage.service.ts
Enhance error handling in network initialization and authentication services. Implement checks to ensure storage services are ready before performing operations.
> Improve error handling and service readiness checks in network and storage services

- src/app/app.component.ts
- src/app/core/components/dashboard/dashboard.component.html
- src/app/core/components/dashboard/dashboard.component.scss
- src/app/core/components/dashboard/dashboard.component.ts
- src/app/core/components/upgrade-config/upgrade-config.component.html
- src/app/core/components/upgrade-config/upgrade-config.component.scss
- src/assets/help-docs/welcome.md
Improve upgrade instructions with detailed navigation guidance and introduce a help button on the dashboard for user assistance.
> Enhance upgrade instructions and add help navigation button to dashboard

- src/app/core/components/upgrade-config/upgrade-config.component.html
- src/app/widgets/widget-tutorial/widget-tutorial.component.html
- src/app/widgets/widget-tutorial/widget-tutorial.component.scss
- src/assets/help-docs/welcome.md
Enhance the clarity and navigation of the tutorial and upgrade documentation. Include detailed instructions for gestures, mouse, and keyboard shortcuts, and improve the overall structure for better user understanding. Add notes to clarify terminology and streamline the content for easier access.
> Refactor tutorial and upgrade documentation for improved clarity

- src/assets/help-docs/datainspector.md
- src/assets/help-docs/embedwidget.md
- src/assets/help-docs/putcontrols.md
- src/assets/help-docs/zones.md
Enhance clarity and detail in the help documentation for various features, including PUT command usage, CORS limitations, and notification management. Address minor grammatical issues and improve user guidance throughout the documentation.
> Update help documentation for Data Inspector, Embed Page Viewer, PUT commands, and Zones configuration

- package.json
- src/app/core/components/dashboard/dashboard.component.ts
- src/app/core/interfaces/widgets-interface.ts
- src/app/core/services/widget.service.ts
- src/app/widget-config/modal-widget-config/modal-widget-config.component.html
- src/app/widgets/gauge-steel/gauge-steel.component.html
- src/app/widgets/widget-horizon/widget-horizon.component.html
- src/app/widgets/widget-horizon/widget-horizon.component.scss
- src/app/widgets/widget-horizon/widget-horizon.component.spec.ts
- src/app/widgets/widget-horizon/widget-horizon.component.ts
- src/assets/svg/icons.svg
Introduce a new Horizon Steel gauge component.
> Add Horizon Steel Components

- CHANGELOG.md
- README.md
- package.json
- src/assets/help-docs/dashboards.md
Bump the package version to 3.8.0, improve the CHANGELOG with recent fixes, and add documentation for the new Pitch & Roll widget.
> Update version to 3.8.0 and enhance documentation

- .github/copilot-instructions.md
- COPILOT.md
- README.md
- src/app/core/utils/svg-animate.util.ts
- src/app/widgets/svg-windsteer/svg-windsteer.component.ts
Introduce high-performance SVG animation utilities to optimize animations in the windsteer component. Update documentation to include new guidelines and usage patterns for these utilities.
> Enhance SVG animation utilities and update documentation

- src/app/app.component.scss
- src/app/app.component.ts
- src/app/core/components/dashboard/dashboard.component.html
- src/app/core/components/dashboard/dashboard.component.ts
- src/app/core/components/menu-notifications/menu-notifications.component.html
- src/app/core/components/menu-notifications/menu-notifications.component.ts
- src/app/core/components/notification-badge/notification-badge.component.html
- src/app/core/components/notification-badge/notification-badge.component.scss
- src/app/core/components/notification-badge/notification-badge.component.ts
- src/app/core/services/notification-overlay.service.ts
- src/app/core/utils/app-overlay-container.ts
- src/main.ts
- src/styles.scss
Introduce a notification overlay service to manage a floating notification badge, improving accessibility and user experience. Update the dashboard to utilize this service and enhance notification handling. Reduce chances of DOM Detached object caused by Gridstack DOM parenting reordering.
> Implement notification overlay service and enhance dashboard notifications

- src/app/widgets/widget-race-timer/widget-race-timer.component.html
- src/app/widgets/widget-race-timer/widget-race-timer.component.scss
- src/app/widgets/widget-race-timer/widget-race-timer.component.ts
Introduce the ability to configure countdown seconds and add sound alerts at the start and when reaching 10 seconds. Update the UI for better interaction and adjust the timer logic to support these features.
Fixes #776
> Enhance Countdown Timer Widget with Configurable Time and Sound Alerts

- src/app/core/components/dialog-dashboard-page-editor/dialog-dashboard-page-editor.component.html
- src/app/core/components/options/display/display.component.html
- src/app/core/components/options/display/display.component.ts
- src/app/core/components/select-icon/select-icon.component.scss
Enhance clarity of text, improve checkbox and toggle functionality, and refine styling for icon selection in the display and dashboard dialog components.
> Minor UI improvements for display and dashboard components

- angular.json
- package.json
- src/app/core/components/app-help/app-help.component.html
- src/app/core/components/app-help/app-help.component.scss
- src/assets/help-docs/kiosk.md
- src/styles.scss
Improve help documentation by integrating PrismJS for syntax highlighting, copy-clipboard, enhancing markdown styles, and refining the formatting of kiosk.md.
> Enhance help documentation and UI with syntax highlighting

- src/app/core/components/widget-host/widget-host.component.html
Change the static dashboard border to a dashed transparent style for improved visibility.
> Fix border style for widget card
